# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FishingWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FishingWeather
	pod 'Moya'
	pod 'Moya-ObjectMapper'
	pod 'SDWebImage'
end
